## Variables from Inventory file - Filename of inventory - hosts.ini
- name: Print variable x and y
  hosts: localhost
  connection: local
  become: true
  vars:
    x: 10
    y: 20
  tasks:
    - name: Print variable x and y
      ansible.builtin.debug:
        msg: x - {{ x }} y - {{ y }}

